# File: .github/workflows/test-check-mp.yml
name: Test Merly Mentor Action

# Trigger on pushes to main (or whatever branch)
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-merly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: ${{vars.MODEL_PATH}}

      - name: Merly Mentor Check MP
        uses: merly-ai/mentor-action@v1
        with:
          mm-key: '${{ secrets.MM_KEY }}'
          checkout-code: false
          path: ${{vars.MODEL_PATH}}
          max_issue_count: 2
          docker-tag: v0.10.2